// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoomTab = "room_tab"

// RoomTab room base info
type RoomTab struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoomName   string `gorm:"column:room_name;not null;comment:room_name" json:"room_name"`                   // room_name
	RuleJSON   string `gorm:"column:rule_json;comment:rule_json" json:"rule_json"`                            // rule_json
	Number     int64  `gorm:"column:number;not null;comment:number" json:"number"`                            // number
	OwnerWxID  string `gorm:"column:owner_wx_id;not null;comment:owner_wx_id" json:"owner_wx_id"`             // owner_wx_id
	CreateTime int64  `gorm:"column:create_time;not null;comment:create time" json:"create_time"`             // create time
	UpdateTime int64  `gorm:"column:update_time;not null;comment:update time" json:"update_time"`             // update time
	IsDelete   int32  `gorm:"column:is_delete;not null;comment:0:valid,1:logically deleted" json:"is_delete"` // 0:valid,1:logically deleted
}

// TableName RoomTab's table name
func (*RoomTab) TableName() string {
	return TableNameRoomTab
}
